// Main
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
// Welcome page
export const UPDATE_WELCOME = 'UPDATE_WELCOME'
export const UPDATE_PAGE_SECTION = 'UPDATE_PAGE_SECTION'
// User page
export const ADD_UPDATE_USER_DATA = 'ADD_UPDATE_USER_DATA'